export const images = {
  PrimaryImage: require('../assets/images/Primary.png'),
  Profile: require('../assets/images/profile.jpg'),
  authBg: require('../assets/images/Authbg.png'),
  logoMain: require('../assets/images/logo.png'),
  user1: require('../assets/images/user.jpeg'),
  user2: require('../assets/images/user1.jpg'),
  user3: require('../assets/images/user2.jpg'),
  back: require('../assets/images/arrow-back.png'),
  editpro: require('../assets/images/editpro.png'),
  search: require('../assets/images/search.png'),
  arrow: require('../assets/images/arrow.png'),
  call_icon: require('../assets/images/call.png'),
  send_icon: require('../assets/images/send.png'),
  close_icon: require('../assets/images/close.png'),
  info: require('../assets/images/info_icon.png'),
  language: require('../assets/images/lang_icon.png'),
  favourite: require('../assets/images/fav_icon.png'),
  payment: require('../assets/images/payment_icon.png'),
  contact: require('../assets/images/contact_icon.png'),
  fav_unselected: require('../assets/images/fav1.png'),
  fav_selected: require('../assets/images/fav2.png'),
  product: require('../assets/images/prdouctimage.png'),
  product1: require('../assets/images/prdouctimage(1).png'),
  product2: require('../assets/images/prdouctimage(2).png'),
  check: require('../assets/images/check.png'),
  showeye: require('../assets/images/showeye.png'),
  hideeye: require('../assets/images/hideeye.png'),
  bell: require('../assets/images/bell.png'),
  cart: require('../assets/images/cart.png'),
  chat: require('../assets/images/chat.png'),
  discount: require('../assets/images/discount.png'),
  shop: require('../assets/images/shop.png'),
  scooter: require('../assets/images/scooter.png'),

  rectblur: require('../assets/images/rectblur.png'),
  heart: require('../assets/images/heart.png'),
  heart_filled: require('../assets/images/heart-filled.png'),
  home: require('../assets/images/home.png'),
  home_icon: require('../assets/images/home-icon.png'),
  office: require('../assets/images/office_icon.png'),
  plus: require('../assets/images/Plus.png'),
  minus: require('../assets/images/Min.png'),
  store: require('../assets/images/store-photo.png'),
  star: require('../assets/images/star.png'),
  location: require('../assets/images/location-pointer.png'),
  plus_slim: require('../assets/images/add_icon.png'),
  orders: require('../assets/images/orders.png'),
  message: require('../assets/images/message.png'),
  profile: require('../assets/images/profile1.png'),
  vapshop: require('../assets/images/vapshop.jpg'),
  vapshop1: require('../assets/images/vapshop1.jpg'),
  offer_image: require('../assets/images/discount-img.png'),
  star: require('../assets/images/sitara.png'),
  nav: require('../assets/images/nav.png'),
  bin_icon: require('../assets/images/bin-icon.png'),
  Scooterr: require('../assets/images/scooter2.png'),
  heart1: require('../assets/images/heart1.png'),
  addcard: require('../assets/images/addcard.png'),
  mastercard: require('../assets/images/mastercard.png'),
  visacard: require('../assets/images/visa.png'),
  COD: require('../assets/images/cod.png'),
};

export const colors = {
  primary: '#715CE4',
  secondary: '#4361EE',
  BtnGreen: '#98FF98',
};

export const FontFamily = {
  Extra_Bold: 'Mona-Sans-ExtraBold',
  Bold: 'Mona-Sans-Bold',
  Semi_Bold: 'Mona-Sans-SemiBold',
  Medium: 'Mona-Sans-Medium',
  Regular: 'Mona-Sans-Regular',
  Light: 'Mona-Sans-Light',
};
